In [ ]:
bank_holidays = {
    'Easter' : (
        pd.date_range(start='25/03/2005', periods=4),
        pd.date_range(start='14/04/2006', periods=4),
        pd.date_range(start='06/04/2007', periods=4),
        pd.date_range(start='21/03/2008', periods=4),
        pd.date_range(start='10/04/2009', periods=4),
        pd.date_range(start='02/04/2010', periods=4)
    ),
    'Mayday' : (
        pd.date_range(start='30/04/2005', periods=3),
        pd.date_range(start='29/04/2006', periods=3),
        pd.date_range(start='05/05/2007', periods=3),
        pd.date_range(start='03/05/2008', periods=3),
        pd.date_range(start='04/05/2009', periods=3),
        pd.date_range(start='01/05/2010', periods=3)
    ),
    'Spring Bank Holiday' : (
        pd.date_range(start='28/05/2005', periods=3),
        pd.date_range(start='27/05/2006', periods=3),
        pd.date_range(start='26/05/2007', periods=3),
        pd.date_range(start='24/05/2008', periods=3),
        pd.date_range(start='23/05/2009', periods=3),
        pd.date_range(start='29/05/2010', periods=3)
    ),
    'Summer Bank Holiday' : (
        pd.date_range(start='28/08/2005', periods=3),
        pd.date_range(start='26/08/2006', periods=3),
        pd.date_range(start='25/08/2007', periods=3),
        pd.date_range(start='23/08/2008', periods=3),
        pd.date_range(start='29/08/2009', periods=3),
        pd.date_range(start='28/08/2010', periods=3)
    ),
    'Christmas' : (
        pd.date_range(start='25/12/2005', periods=4),
        pd.date_range(start='23/12/2006', periods=4),
        pd.date_range(start='25/12/2007', periods=4),
        pd.date_range(start='25/12/2008', periods=4),
        pd.date_range(start='25/12/2009', periods=4),
        pd.date_range(start='25/12/2010', periods=4),
),
    'New Year' : (
        pd.date_range(start='01/01/2005', periods=3),
        pd.date_range(start='31/12/2006', periods=3),
        pd.date_range(start='30/12/2007', periods=3),
        pd.date_range(start='29/12/2008', periods=3),
        pd.date_range(start='01/01/2009', periods=3),
        pd.date_range(start='01/01/2010', periods=3)
)
}
bh1 = {k: pd.DataFrame(list(zip(*v)), columns=['2005', '2006', '2007', '2008', '2009', '2010']) for k, v in bank_holidays.items()}
df_bh = pd.concat(bh1).reset_index(level=1, drop=True)
df_bh

In [ ]:
bank_hols_2005 = {
    'Easter' : (pd.date_range(pd.to_datetime('25/03/2005'), periods=4)),
    'Mayday' : (pd.date_range(pd.to_datetime('30/04/2005'), periods=3)),
    'Spring Bank Holiday' : (pd.date_range(pd.to_datetime('28/05/2005'),
                                           periods=3)
                             ),
    'Summer Bank Holiday' : (pd.date_range(pd.to_datetime('28/08/2005'),
                                           periods=3)
                             ),
    'Christmas' : (pd.date_range(pd.to_datetime('25/12/2005'), periods=3)),
    'New Year' : (pd.date_range(pd.to_datetime('01/01/2005'), periods=3))
}

bank_hols_2005 = {v:k for k, lst in bank_hols_2005.items() for v in lst}

bank_hols_2006 = {
    'Easter' : (pd.date_range(pd.to_datetime('14/04/2006'), periods=4)),
    'Mayday' : (pd.date_range(pd.to_datetime('29/04/2006'), periods=3)),
    'Spring Bank Holiday' : (pd.date_range(pd.to_datetime('27/05/2006'),
                                           periods=3)
                             ),
    'Summer Bank Holiday' : (pd.date_range(pd.to_datetime('26/08/2006'),
                                           periods=3)
                             ),
    'Christmas' : (pd.date_range(pd.to_datetime('23/12/2006'), periods=4)),
    'New Year' : (pd.date_range(pd.to_datetime('31/12/2006'), periods=3))
}

bank_hols_2006 = {v:k for k, lst in bank_hols_2006.items() for v in lst}

bank_hols_2007 = {
    'Easter' : (pd.date_range(pd.to_datetime('06/04/2007'), periods=4)),
    'Mayday' : (pd.date_range(pd.to_datetime('05/05/2007'), periods=3)),
    'Spring Bank Holiday' : (pd.date_range(pd.to_datetime('26/05/2007'),
                                           periods=3)
                             ),
    'Summer Bank Holiday' : (pd.date_range(pd.to_datetime('25/08/2007'),
                                           periods=3)
                             ),
    'Christmas' : (pd.date_range(pd.to_datetime('25/12/2007'), periods=4)),
    'New Year' : (pd.date_range(pd.to_datetime('30/12/2007'), periods=3))
}

bank_hols_2007 = {v:k for k, lst in bank_hols_2007.items() for v in lst}

bank_hols_2008 = {
    'Easter' : (pd.date_range(pd.to_datetime('21/03/2008'), periods=4)),
    'Mayday' : (pd.date_range(pd.to_datetime('03/05/2008'), periods=3)),
    'Spring Bank Holiday' : (pd.date_range(pd.to_datetime('24/05/2008'),
                                           periods=3)
                             ),
    'Summer Bank Holiday' : (pd.date_range(pd.to_datetime('23/08/2008'),
                                           periods=3)
                             ),
    'Christmas' : (pd.date_range(pd.to_datetime('25/12/2008'), periods=4)),
    'New Year' : (pd.date_range(pd.to_datetime('29/12/2008'), periods=4))
}

bank_hols_2008 = {v:k for k, lst in bank_hols_2008.items() for v in lst}

bank_hols_2009 = {
    'Easter' : (pd.date_range(pd.to_datetime('10/04/2009'), periods=4)),
    'Mayday' : (pd.date_range(pd.to_datetime('02/05/2009'), periods=3)),
    'Spring Bank Holiday' : (pd.date_range(pd.to_datetime('23/05/2009'),
                                           periods=3)
                             ),
    'Summer Bank Holiday' : (pd.date_range(pd.to_datetime('29/08/2009'),
                                           periods=3)
                             ),
    'Christmas' : (pd.date_range(pd.to_datetime('25/12/2009'), periods=4)),
    'New Year' : (pd.date_range(pd.to_datetime('01/01/2009'), periods=2))
}

bank_hols_2009 = {v:k for k, lst in bank_hols_2009.items() for v in lst}

bank_hols_2010 = {
    'Easter' : (pd.date_range(pd.to_datetime('02/04/2010'), periods=4)),
    'Mayday' : (pd.date_range(pd.to_datetime('01/05/2010'), periods=3)),
    'Spring Bank Holiday' : (pd.date_range(pd.to_datetime('29/05/2010'),
                                           periods=3)
                             ),
    'Summer Bank Holiday' : (pd.date_range(pd.to_datetime('28/08/2010'),
                                           periods=3)
                             ),
    'Christmas' : (pd.date_range(pd.to_datetime('25/12/2010'), periods=4)),
    'New Year' : (pd.date_range(pd.to_datetime('01/01/2010'), periods=4))
}

bank_hols_2010 = {v:k for k, lst in bank_hols_2010.items() for v in lst}

In [ ]:
bank_hols_2005 = {
    'Easter' : (pd.date_range(pd.to_datetime('25/03/2005'), periods=4)),
    'Mayday' : (pd.date_range(pd.to_datetime('30/04/2005'), periods=3)),
    'Spring Bank Holiday' : (pd.date_range(pd.to_datetime('28/05/2005'),
                                           periods=3)
                             ),
    'Summer Bank Holiday' : (pd.date_range(pd.to_datetime('28/08/2005'),
                                           periods=3)
                             ),
    'Christmas' : (pd.date_range(pd.to_datetime('25/12/2005'), periods=3)),
    'New Year' : (pd.date_range(pd.to_datetime('01/01/2005'), periods=3))
}

bank_hols_2005 = {v:k for k, lst in bank_hols_2005.items() for v in lst}

bank_hols_2006 = {
    'Easter' : (pd.date_range(pd.to_datetime('14/04/2006'), periods=4)),
    'Mayday' : (pd.date_range(pd.to_datetime('29/04/2006'), periods=3)),
    'Spring Bank Holiday' : (pd.date_range(pd.to_datetime('27/05/2006'),
                                           periods=3)
                             ),
    'Summer Bank Holiday' : (pd.date_range(pd.to_datetime('26/08/2006'),
                                           periods=3)
                             ),
    'Christmas' : (pd.date_range(pd.to_datetime('23/12/2006'), periods=4)),
    'New Year' : (pd.date_range(pd.to_datetime('31/12/2006'), periods=3))
}

bank_hols_2006 = {v:k for k, lst in bank_hols_2006.items() for v in lst}

bank_hols_2007 = {
    'Easter' : (pd.date_range(pd.to_datetime('06/04/2007'), periods=4)),
    'Mayday' : (pd.date_range(pd.to_datetime('05/05/2007'), periods=3)),
    'Spring Bank Holiday' : (pd.date_range(pd.to_datetime('26/05/2007'),
                                           periods=3)
                             ),
    'Summer Bank Holiday' : (pd.date_range(pd.to_datetime('25/08/2007'),
                                           periods=3)
                             ),
    'Christmas' : (pd.date_range(pd.to_datetime('25/12/2007'), periods=4)),
    'New Year' : (pd.date_range(pd.to_datetime('30/12/2007'), periods=3))
}

bank_hols_2007 = {v:k for k, lst in bank_hols_2007.items() for v in lst}

bank_hols_2008 = {
    'Easter' : (pd.date_range(pd.to_datetime('21/03/2008'), periods=4)),
    'Mayday' : (pd.date_range(pd.to_datetime('03/05/2008'), periods=3)),
    'Spring Bank Holiday' : (pd.date_range(pd.to_datetime('24/05/2008'),
                                           periods=3)
                             ),
    'Summer Bank Holiday' : (pd.date_range(pd.to_datetime('23/08/2008'),
                                           periods=3)
                             ),
    'Christmas' : (pd.date_range(pd.to_datetime('25/12/2008'), periods=4)),
    'New Year' : (pd.date_range(pd.to_datetime('29/12/2008'), periods=4))
}

bank_hols_2008 = {v:k for k, lst in bank_hols_2008.items() for v in lst}

bank_hols_2009 = {
    'Easter' : (pd.date_range(pd.to_datetime('10/04/2009'), periods=4)),
    'Mayday' : (pd.date_range(pd.to_datetime('02/05/2009'), periods=3)),
    'Spring Bank Holiday' : (pd.date_range(pd.to_datetime('23/05/2009'),
                                           periods=3)
                             ),
    'Summer Bank Holiday' : (pd.date_range(pd.to_datetime('29/08/2009'),
                                           periods=3)
                             ),
    'Christmas' : (pd.date_range(pd.to_datetime('25/12/2009'), periods=4)),
    'New Year' : (pd.date_range(pd.to_datetime('01/01/2009'), periods=2))
}

bank_hols_2009 = {v:k for k, lst in bank_hols_2009.items() for v in lst}

bank_hols_2010 = {
    'Easter' : (pd.date_range(pd.to_datetime('02/04/2010'), periods=4)),
    'Mayday' : (pd.date_range(pd.to_datetime('01/05/2010'), periods=3)),
    'Spring Bank Holiday' : (pd.date_range(pd.to_datetime('29/05/2010'),
                                           periods=3)
                             ),
    'Summer Bank Holiday' : (pd.date_range(pd.to_datetime('28/08/2010'),
                                           periods=3)
                             ),
    'Christmas' : (pd.date_range(pd.to_datetime('25/12/2010'), periods=4)),
    'New Year' : (pd.date_range(pd.to_datetime('01/01/2010'), periods=4))
}

bank_hols_2010 = {v:k for k, lst in bank_hols_2010.items() for v in lst}

In [ ]:
df_bank_hols = df_accident
df_bank_hols['bank_holidays_2005'] = df_bank_hols['date'].map(bank_hols_2005)
df_bank_hols['bank_holidays_2006'] = df_bank_hols['date'].map(bank_hols_2006)
df_bank_hols['bank_holidays_2007'] = df_bank_hols['date'].map(bank_hols_2007)
df_bank_hols['bank_holidays_2008'] = df_bank_hols['date'].map(bank_hols_2008)
df_bank_hols['bank_holidays_2009'] = df_bank_hols['date'].map(bank_hols_2009)
df_bank_hols['bank_holidays_2010'] = df_bank_hols['date'].map(bank_hols_2010)
df_bank_hols['bank_holidays_2009'].value_counts().sum() / 19

In [ ]:
df_bank_hols['bank_holidays_2007'].value_counts().sum() / 19

In [ ]:

fig, ax = plt.subplots(3, 2, figsize=(30,25))
df_bank_hols.bank_holidays_2005 = pd.Categorical(values=df_bank_hols.bank_holidays_2005,
                                    categories=['New Year',
                                                'Christmas',
                                                'Easter', 'Mayday',
                                                'Spring Bank Holiday',
                                                'Summer Bank Holiday'
                                                ]
                                    ) # Set the order for the column as you want
df_bank_hols.sort_values(['bank_holidays_2005'], inplace=True) # Sort the column

sns.histplot(data=df_bank_hols, y='bank_holidays_2005', palette='pastel', bins=4, ax=ax[0, 0], hue='accident_severity')

df_bank_hols.bank_holidays_2006 = pd.Categorical(values=df_bank_hols.bank_holidays_2006,
                                    categories=['New Year',
                                                'Christmas',
                                                'Easter', 'Mayday',
                                                'Spring Bank Holiday',
                                                'Summer Bank Holiday'
                                                ]
                                    ) # Set the order for the column as you want
df_bank_hols.sort_values(['bank_holidays_2006'], inplace=True) # Sort the column

sns.histplot(data=df_bank_hols, y='bank_holidays_2006', palette='pastel', bins=4, ax=ax[0, 1], hue='accident_severity')

df_bank_hols.bank_holidays_2007 = pd.Categorical(values=df_bank_hols.bank_holidays_2007,
                                    categories=['New Year',
                                                'Christmas',
                                                'Easter', 'Mayday',
                                                'Spring Bank Holiday',
                                                'Summer Bank Holiday'
                                                ]
                                    ) # Set the order for the column as you want
df_bank_hols.sort_values(['bank_holidays_2007'], inplace=True) # Sort the column

sns.histplot(data=df_bank_hols, y='bank_holidays_2007', palette='pastel', bins=4, ax=ax[1, 0], hue='accident_severity')

df_bank_hols.bank_holidays_2008 = pd.Categorical(values=df_bank_hols.bank_holidays_2008,
                                    categories=['New Year',
                                                'Christmas',
                                                'Easter', 'Mayday',
                                                'Spring Bank Holiday',
                                                'Summer Bank Holiday'
                                                ]
                                    ) # Set the order for the column as you want
df_bank_hols.sort_values(['bank_holidays_2008'], inplace=True) # Sort the column

sns.histplot(data=df_bank_hols, y='bank_holidays_2008', palette='pastel', bins=4, ax=ax[1, 1], hue='accident_severity')

df_bank_hols.bank_holidays_2009 = pd.Categorical(values=df_bank_hols.bank_holidays_2009,
                                    categories=['New Year',
                                                'Christmas',
                                                'Easter', 'Mayday',
                                                'Spring Bank Holiday',
                                                'Summer Bank Holiday'
                                                ]
                                    ) # Set the order for the column as you want
df_bank_hols.sort_values(['bank_holidays_2009'], inplace=True) # Sort the column

sns.histplot(data=df_bank_hols, y='bank_holidays_2009', palette='pastel', bins=4, ax=ax[2, 0], hue='accident_severity')

df_bank_hols.bank_holidays_2010 = pd.Categorical(values=df_bank_hols.bank_holidays_2010,
                                    categories=['New Year',
                                                'Christmas',
                                                'Easter', 'Mayday',
                                                'Spring Bank Holiday',
                                                'Summer Bank Holiday'
                                                ]
                                    ) # Set the order for the column as you want
df_bank_hols.sort_values(['bank_holidays_2010'], inplace=True) # Sort the column

sns.histplot(data=df_bank_hols,
                  y='bank_holidays_2010',
                  palette='pastel',
                  bins=12, ax=ax[2, 1],
                  hue='accident_severity'
                  )

plt.show()

In [ ]:
fig, ax = plt.subplots(3, 2, figsize=(30, 20))

sns.histplot(df_bank_hols[df_bank_hols['accident_severity'] == 'Fatal'],
             y='bank_holidays_2005',
             alpha=0.6, bins=50, ax=ax[0, 0]
             ).set(title=f'2005: Fatal')

sns.histplot(df_bank_hols[df_bank_hols["accident_severity"] == "Fatal"],
             y='bank_holidays_2006', color='orange',
             alpha=0.6, bins=50, ax=ax[0, 1]
             ).set(title=f'2006: Fatal')

sns.histplot(df_bank_hols[df_bank_hols["accident_severity"] == "Fatal"],
             y='bank_holidays_2007', color='brown',
             alpha=0.6, bins=50, ax=ax[1, 0]
             ).set(title=f'2007: Fatal')

sns.histplot(df_bank_hols[df_bank_hols["accident_severity"] == "Fatal"],
             y='bank_holidays_2008', color='purple',
             alpha=0.6, bins=50, ax=ax[1, 1]
             ).set(title=f'2008: Fatal')

sns.histplot(df_bank_hols[df_bank_hols["accident_severity"] == "Fatal"],
             y='bank_holidays_2009', color='green',
             alpha=0.6, bins=50, ax=ax[2, 0]
             ).set(title=f'2009: Fatal')

sns.histplot(df_bank_hols[df_bank_hols["accident_severity"] == "Fatal"],
             y='bank_holidays_2010', color='maroon',
             alpha=0.6, bins=50, ax=ax[2, 1]
             ).set(title=f'2010: Fatal')

plt.show()  ## and plot

In [ ]:
fatal = len(df_accident[((df_accident['accident_severity'] == 'Fatal') & (df_accident['year'] == 2005))])
fatal

In [ ]:
hols = len(df_accident[
            ((df_accident['accident_severity'] =='Fatal') & (df_accident['date'] >= '03/25/2005'))
            & ((df_accident['date'] <= '03/28/2005'))
        ])
hols